backend:
  name: github
  repo: Alec-Raymond/offpost_media_website
  branch: main

# These are the default fallback folders
media_folder: "assets/portfolio"
public_folder: "/assets/portfolio"

collections:
  - name: "portfolio"
    label: "Portfolio Data"
    delete: false
    files:
      - name: "albums_list"
        label: "Manage Albums"
        file: "albums.json"
        format: "json"
        fields:
          - name: "albums"
            label: "Albums"
            widget: "list"
            summary: "{{fields.title}} (ID: {{fields.id}})"
            add_to_top: false
            fields:
              - {label: "Album ID (Lowercase, no spaces)", name: "id", widget: "string"}
              - {label: "Album Title", name: "title", widget: "string"}
              - {label: "Show Title on Cover?", name: "showTitle", widget: "boolean", default: true}
              - label: "Photos"
                name: "photos"
                widget: "list"
                summary: "{{fields.photo}}"
                fields:
                  - label: "Photo"
                    name: "photo"
                    widget: "image"
                    # Decap doesn't support {{id}} inside a list in a file collection.
                    # All photos will save globally to raw, and our script will organize them.
                    media_folder: "assets/portfolio/raw"
                    public_folder: "assets/portfolio/raw"
